#Spring Boot setting 하는 곳
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lecture 
    username: root
    password: root

mybatis:
  mapper-locations:
    - /mappers/*.xml